apiVersion: v1
kind: Pod
metadata:
  name: secure-db
  labels:
    app: database

spec:
      containers:
      - name: redis
        image: redis:alpine
        ports: 
         - containerPort: 6379


---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
     selector:
       app: database
     ports:
     - protocol: TCP
       port: 6379
       targetPort: 6379
