apiVersion: v1
kind: Pod
metadata: 
   name: hacker
   labels:
    app: hacker
spec:
 containers:
    - name: network-tools
      image: praqma/network-multitool
      command: ["/bin/sh", "-c", "sleep 3600"]